### ISSUE TITLE
Java 11 build not available due to gradle version being so old

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/mapfish-print#65] opened 2023-07-05 10:25 UTC
Cross-referencing https://github.com/mapfish/mapfish-print-v2/issues/11

GeoTools now requires Java 11, and as part [OpenGIS Harmonization](https://www.osgeo.org/opengis-harmonization/) we need to change some package names in GeoTools requiring a new release of mapfish-print-v2 for downstream projects GeoServer and GeoNode.

- Presently: gradle version 3, works with Java 8 (not Java 11) and uses plugins jetty and maven
- Minimim: gradle version 5, works with Java 11, requires upgrade to plugins getty and maven-plublish

@tdipisa are you aware of this? Is it something that has been already discussed?
@aaime might add more details.

**Comment by aaime** [comment] 2023-07-05 10:38
That ticket was the first communication towards the community. 
I've also reported in private to @giohappy on Monday July 2nd.

The details in that ticket are all we know, but we can set up a meeting to discuss it better if you want.
In short:
- GeoServer depends on GeoTools, whose public API is going to change significantly to avoid Martin Desriusseaux/OGC to use us for using the ``org.opengis`` Java package
- MapFish v2 also depends on GeoTools, a very old version of it. We need to upgrade it t the latest, or it won't work anymore with the more recent GeoTools version with different package names, but the old project does not even build against it, because it cannot build with Java 11. (it's working in the current version of GeoServer just because of a lucky accident).

```mermaid
graph TD;
    GeoServer-->MapfishPrintV2;
    GeoServer-->GeoTools
    MapfishPrintV2-->GeoTools;
```

The mapfish-print version used directly by MapStore is likely not affected, as MapStore does not have a GeoTools dependency of its own (as far as I know, at least).

**Comment by jodygarnett** [comment] 2023-08-25 10:17
Please see https://github.com/mapfish/mapfish-print-v2/pull/12 branch which merges all the work here into something that can be updated for geotools refactor.

I worked very hard @aaime with and @sebr72(camptocamp) at the code sprint to try and come up with a solution that would satisfy GeoNode community and be support out-of-the box by gs-printing module.

**Comment by tdipisa** [comment] 2023-09-12 07:57
More info also [here](https://github.com/geosolutions-it/EMSA-OGC/issues/1756) for internal coordination ad testing purposes.

**Comment by giohappy** [comment] 2023-09-12 08:39
@tdipisa let me know when tests on your side are done, then I will setup the tasks to upgrade GeoNode to the new mapfish print libs.

**Comment by jodygarnett** [comment] 2023-09-12 14:08
Thanks, we want the GeoNode community to be happy out-of-the-box before making this GeoServer release.

**Comment by jodygarnett** [comment] 2023-09-12 21:55
> More info also [here](https://github.com/geosolutions-it/EMSA-OGC/issues/1756)

I cannot see that issue, perhaps it is a private repository.

**Comment by tdipisa** [comment] 2023-09-13 10:38
> > More info also [here](https://github.com/geosolutions-it/EMSA-OGC/issues/1756)
> 
> I cannot see that issue, perhaps it is a private repository.

That's only for internal coordination for testing purposes @jodygarnett

**Comment by tdipisa** [comment] 2023-09-13 15:33
@offtherailz the new artifact is now ready on [GS MVN repo](https://maven.geo-solutions.it/org/mapfish/print/print-lib/2.3-SNAPSHOT/) to be used for MS dev. @ElenaGallo will be involved for functional tests there.

**Comment by jodygarnett** [comment] 2023-09-13 19:39
> That's only for internal coordination for testing purposes @jodygarnett

That was my subtle reminder that you are on a public communication channel :)

**Comment by jodygarnett** [comment] 2023-09-13 19:46
Note that use of https://maven.geo-solutions.it/org/mapfish/print/print-lib/2.3-SNAPSHOT/ is not going to work well for anyone as there is a conflict between this and repo.osgeo.org for the same artifact coordinate. If you wish to have a fork use a different classifier or group id etc….

The correct org.mapfish.print:print-lib:2.2-SNAPSHOT is already available from build.geoserver.org nightly builds packaged in geosever printing extension and ready to use.

**Closed as completed** 2023-09-15 13:41 UTC
Labels: enhancement, MapStore, MapFish, internal

**Comment by tdipisa** [comment] 2023-09-19 10:26
@jodygarnett @aaime @giohappy 
The updated print-lib has been integrated in MS master branch through https://github.com/geosolutions-it/MapStore2/pull/9453 and tested in [DEV environment](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/) by comparing the output with the one of [QA](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/) (that provides the old print-lib version from the GeoSolutions fork). 

The test has been performed using [this map](https://github.com/geosolutions-it/mapfish-print/files/12658603/map_print_test.zip) with the [MapStore printing tool](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/print/). All layout combinations provided by that tool have been tested as well as other available options such as:

- output format
- legend options
- coordinate system

### Test result
Comparing prints between DEV and QA using the same options, the outputs are the same. There are therefore no regressions from tested use cases.

Printing outputs derived from the tests are available [here](https://drive.google.com/file/d/1XYTdBokLuN0S_PQfJWMlHlpOQ68m0ala/view?usp=sharing).

The only issue found during tests is captured by https://github.com/geosolutions-it/MapStore2/issues/9459 and need to be further investigated. It doesn't seems anyway connected with printing capabilities.

The new print-lib version will be anyway available for the next major version of MapStore v2024.01.00. In the meantime it will remain in MS master branch for further tests during next months.

**Comment by giohappy** [comment] 2023-09-19 10:54
@giohappy so we can proceed with the upgrade of the print-lib in Geoserver for GeoNode, right @tdipisa?

**Comment by tdipisa** [comment] 2023-09-19 12:24
yes, @giohappy

**Comment by giohappy** [comment] 2023-09-19 14:35
FYI A task for testing the new plugin in GeoNode has been created https://github.com/GeoNode/geoserver-geonode-ext/issues/175
